# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr: none

variables: 
  # Service connection as configured in project settings
  prodConnection: 'PAS-Prod'
  # App name
  prodApp: 'PAS-UI'

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: Install
      inputs: 
        command: custom
        customCommand: ci
        workingDir: '$(Build.SourcesDirectory)/webapp'
        verbose: false
        
    - task: Npm@1
      displayName: Build
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)/webapp'
        customCommand: 'run build'

    - task: ArchiveFiles@2
      displayName: 
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/webapp'
        includeRootFolder: false

    - task: PublishPipelineArtifact@0
      displayName: Publish Artifact
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'
        ArtifactName: webapp

- stage: prod
  displayName: Deploy
  dependsOn: build
  jobs:
  - deployment: deployProd
    displayName: Deploy Prod
    environment: PAS-UI-prod
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'PAS-Prod'
              appType: 'webAppLinux'
              appName: $(prodApp)
              runtimeStack: 'NODE|14-lts'
              startUpCommand: 'npm run start'
              